# To change worker configuration, change worker number, e.g., worker1 to worker1, and the config file accordingly.
# and also --conf=config_docker_01_onr_1.yaml to the desired config file.
# Run command: docker compose -p 'worker1' up 
networks:
  jaw-network: {}

services:
  logic:
    build: .
    image: jaw-logic
    # container_name: jaw4c-logic    
    volumes:
      # Mount data to nms
      - /home/enyenl/JAW4C:/JAW4C
      - /home/enyenl/nms/enyenl_archive_0/archive_2026_jan12_distribution_1_0/name_mapping.json:/JAW4C/JAW4C-WebArchive/archive/name_mapping.json:ro
      - /home/enyenl/nms/jan27-jaw4c-analysis/10_all:/JAW4C/JAW4C-JAW/data
      # Foxhound
      - /home/enyenl/nms/foxhound:/JAW4C/JAW4C-JAW/crawler/foxhound:ro
      # Docker socket for Docker-in-Docker (DinD)
      - /var/run/docker.sock:/var/run/docker.sock
      # node_modules (anonymous volumes for faster rebuilds)
      - /JAW4C/JAW4C-JAW/crawler/node_modules
      - /JAW4C/JAW4C-JAW/dynamic/node_modules
      - /JAW4C/JAW4C-JAW/engine/node_modules
      - /JAW4C/JAW4C-JAW/engine/lib/jaw/dom-points-to
      - /JAW4C/JAW4C-JAW/engine/lib/jaw/normalization
      - /JAW4C/JAW4C-JAW/driver/node_modules      
      - /JAW4C/JAW4C-JAW/analyses/cve_vuln/node_modules
      - /JAW4C/JAW4C-JAW/engine/lib/jaw/aliasing
      - /JAW4C/JAW4C-DEBUN/node_modules
      # test node_modules (anonymous volumes for faster test rebuilds)
      - /JAW4C/JAW4C-JAW/tests/pipeline_test/sites/integration_test/library_detection/test_jquery_bundle_dev/node_modules
      - /JAW4C/JAW4C-JAW/tests/pipeline_test/sites/integration_test/library_detection/test_jquery_bundle/node_modules
      - /JAW4C/JAW4C-JAW/tests/pipeline_test/sites/integration_test/library_detection/test_lodash_bundle/node_modules
      - /JAW4C/JAW4C-JAW/tests/pipeline_test/sites/integration_test/static_analysis/test_initial_decl_assignment/node_modules
      - /JAW4C/JAW4C-JAW/tests/pipeline_test/sites/integration_test/static_analysis/test_initial_decl_cfg/node_modules
      - /JAW4C/JAW4C-JAW/tests/pipeline_test/sites/integration_test/static_analysis/test_initial_decl_function_arg/node_modules
      - /JAW4C/JAW4C-JAW/tests/pipeline_test/sites/integration_test/static_analysis/test_initial_decl_function_call/node_modules
      - /JAW4C/JAW4C-JAW/tests/pipeline_test/sites/integration_test/static_analysis/test_jquery_CVE-2020-7656/node_modules
      - /JAW4C/JAW4C-JAW/tests/pipeline_test/sites/integration_test/static_analysis/test_vuln_bund_jquery_CVE-2020-7656_dev/node_modules
      - /JAW4C/JAW4C-JAW/tests/pipeline_test/sites/integration_test/static_analysis/test_vuln_bund_jquery_CVE-2020-7656/node_modules
      - /JAW4C/JAW4C-JAW/tests/pipeline_test/sites/integration_test/static_analysis/test_vuln_bund_vary_call_jquery_CVE-2020-7656/node_modules
      - /JAW4C/JAW4C-JAW/tests/pipeline_test/sites/integration_test/taint_analysis/test_jquery_vuln_taint_s1_CVE-2020-7656/node_modules
      - /JAW4C/JAW4C-JAW/tests/pipeline_test/sites/integration_test/vuln_db_query/test_no_vuln_version/node_modules
      - /JAW4C/JAW4C-JAW/tests/pipeline_test/sites/integration_test/vuln_db_query/test_vuln_match_dev/node_modules
      - /JAW4C/JAW4C-JAW/tests/pipeline_test/sites/integration_test/vuln_db_query/test_vuln_match/node_modules
      #- /JAW4C/JAW4C-JAW/tests/pipeline_test
    # neo4j requests shouldn't go through proxy but all of the others should to use web archive
    # environment:
    #   HTTP_PROXY: http://proxy:8002
    #   HTTPS_PROXY: http://proxy:8002
    environment:
      - WORKER_NAME=worker1
    networks:
      - jaw-network
    depends_on:
      - db
      - proxy
    deploy:
      resources:
        limits:
          memory: 8g
        reservations:
          memory: 6g
    command: >
      sh -c "python3 -m run_pipeline --conf=/JAW4C/JAW4C-JAW/config_docker_10_nodejs_1.yaml"
# sh -c "while [ 1 ]; do echo '' > /dev/null; done"
# sh -c "python3 -m run_pipeline --conf=config_docker_01_onr_1.yaml"
# sh -c "cd tests/pipeline_test && python3 test_run.py --action analysis --test integration_test/static_analysis/test_jq_CVE-2020-7656 --config=/JAW4C/JAW4C-JAW/config_docker.yaml"

  # neo4j:
  #   image: neo4j:4.4
  #   container_name: neo4j
  #   environment:
  #     NEO4J_AUTH: "neo4j/root"
  #     NEO4J_apoc_export_file_enabled: "true"
  #     NEO4J_apoc_import_file_enabled: "true"
  #     NEO4J_apoc_import_file_use__neo4j__config: "true"
  #     NEO4JLABS_PLUGINS: '["apoc"]'
  #     NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
  #   volumes:
  #     - ./neo4j/data:/data
  #     - ./neo4j/logs:/logs
  #   #   # Only mount import files if needed
  #   #   - ./import:/var/lib/neo4j/import:ro
  #   ports:
  #     - "7474:7474"  # HTTP
  #     - "7687:7687"  # Bolt
  #   networks:
  #     - jaw-network

  db:
    build: ./vuln_db_llm
    # container_name: jaw4c-vulndb
    networks:
      - jaw-network
    environment:
      POSTGRES_USER: vulndb_annotated
      POSTGRES_PASSWORD: vulndb_pwd
      POSTGRES_DB: vulndb_annotated
    volumes:
      - ./vuln_db_llm/pgdata/worker1:/var/lib/postgresql/data
      - ./vuln_db_llm/advisories_exploits.sql:/docker-entrypoint-initdb.d/advisories_exploits.sql:ro
    deploy:
          resources:
            limits:
              memory: 256m
    restart: unless-stopped
  proxy:
    build: ./JAW4C-WebArchive
    # container_name: jaw4c-webarchive
    networks:
      - jaw-network
    volumes:
      - /home/enyenl/nms/enyenl_archive_0/archive_2026_jan12_distribution_1_0:/proxy/archive_2026_jan12_distribution_1_0:ro
    # ports:
    #   - "8002:8002"
    environment:
      - PROXY_VOLUME_PATH=/proxy
      - PROXY_ARCHIVE=archive_2026_jan12_distribution_1_0
    deploy:
          resources:
            limits:
              memory: 6g
            reservations:
              memory: 1g
    restart: unless-stopped
