services:
  jaw4c-ui:
    build: .
    container_name: jaw4c-ui
    ports:
      - "3001:3001"
      - "9229:9229"
    volumes:
      # Mount the JAW4C-JAW data directory for read-only access
      - ../JAW4C-JAW/data:/app/../JAW4C-JAW/data:ro
      - ./site-cache/review:/app/../JAW4C-JAW/data/review
      - ./site-cache:/app/site-cache
     # Mount source code for live updates (no rebuild needed for code changes)
      - ./server.js:/app/server.js:ro
      - ./public:/app/public:ro
      - ./views:/app/views:ro
      - ./tranco_NN23W.csv:/app/tranco_NN23W.csv:ro
      - ./lib_mapping.json:/app/lib_mapping.json:ro
      - ./entrypoint.sh:/app/entrypoint.sh:ro
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - JAW4C_MODE=prod
      - FILE_READ_CONCURRENCY=60
    entrypoint: ["sh", "/app/entrypoint.sh"]
