services:
  jaw4c-ui:
    build: .
    container_name: jaw4c-ui
    ports:
      - "3001:3001"
    volumes:
      # Mount the JAW4C-JAW data directory for read-only access
      - /home/enyenl/nms/jan20-jaw4c-crawl/all:/app/../JAW4C-JAW/data:ro
      - /home/enyenl/nms/jan20-jaw4c-crawl/all/review:/app/../JAW4C-JAW/data/review
      - ./jan20-jaw4c-crawl/site-cache:/app/site-cache
     # Mount source code for live updates (no rebuild needed for code changes)
      - ./server.js:/app/server.js:ro
      - ./public:/app/public:ro
      - ./views:/app/views:ro
    restart: unless-stopped
    environment:
      - NODE_ENV=production
